### ISSUE TITLE
If there is a breaking change, then why is it 0.6 and not 1.0?

### ISSUE THREAD

**Issue by felixfbecker** [KenPowers/gulp-cheerio#11]

**Comment by knpwrs** [comment]
First of all, calm down. I normally don't respond to rudeness.

Second, to quote the [`semver` website](http://semver.org/):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Third, `1.0.0` is probably coming at some point in the future.

Fourth, calm down.

**Comment by felixfbecker** [comment]
Thanks for the answer. I edited my title after I noticed that it sounded more rude than I intended it to be.

**Comment by caillou** [comment]
@knpwrs I just started using this module and the `BREAKING CHANGE` in the `Readme.md` confused me as well.

I then found this issue.

From my point of view, having a library that can not guarantee a stable API within the `minor` and `patch` versions, forces me to lock the version numer in my `package.json`.

Would you consider moving to a 1.0.0 version? Or is this project currently abandoned?

**Comment by knpwrs** [comment]
Just published a `v1.0.0`.

**Comment by caillou** [comment]
Thank you!
