### ISSUE TITLE
Cache parsed html/xml 

### ISSUE THREAD

**Issue by w0rm** [KenPowers/gulp-cheerio#7]
It would be great if gulp-cheerio cached parsed html/xml in gulp file objects so it could be reused in other gulp plugins e.g. in my gulp-svgstore.

**Comment by w0rm** [comment]
Sure, `file.cheerio` is fine. Will implement this in gulp-svgstore on this weekend.

**Comment by KenPowers** [comment]
Published version `0.4.0` to npm. This version also defines cheerio `0.*` as a peer dependency, I suggest you do the same in `gulp-svgstore`

**Comment by w0rm** [comment]
@KenPowers good, I just published `gulp-svgstore` 4.0.0 with examples of using with gulp-cheerio instead of hacky transformSvg callback.
