### ISSUE TITLE
Provide file object in run function

### ISSUE THREAD

**Issue by w0rm** [KenPowers/gulp-cheerio#8]
Sometimes it may be useful to have file object that is processed.
For example to retrieve some additional information based on file name from config.

**Comment by KenPowers** [comment]
Just got my wisdom teeth out. I'll take a pull request or otherwise get around to this later.

**Comment by w0rm** [comment]
How would you like it to be implemented? If I add it like this: `function run($, file, done)` then it will break current api.

**Comment by KenPowers** [comment]
There are a few things we could do. We could add `file` to the `$` object (using `defineProperty` so it isn't enumerable) or we could execute `run` in a context such that `this === file` or `this.file === file`.

I'm fine with either approach. What are your thoughts?

**Comment by w0rm** [comment]
@KenPowers I don't like either way, patching $ is not a good idea, and neither is passing function argument in this. It is better to have `function run($, file, done)` and bump major version because of changed api. Or, if you want compatibility, then maybe it is possible to check 2nd argument to be gulp.File instance, and if its not, use it as done callback.

**Comment by KenPowers** [comment]
I was interested in an API change of deprecating the option to pass in a configuration object. It's not really necessary anymore now that `cheerio` is a peer dependency.

The problem with checking the second argument is that we are supplying the argument. So maybe having three arguments and requiring all three for async would be the best thing to do.

**Comment by KenPowers** [comment]
This would also mean moving the parser options to just be the second argument to our exported function.

**Comment by w0rm** [comment]
Peer dependencies will be deprecated, so I'm not sure if its a good idea https://github.com/npm/npm/issues/6565

**Comment by KenPowers** [comment]
Ugh. Regardless, I'm still interested in deprecating the configuration object. I can't think of a case where I've ever had to substitute my own version of cheerio, especially with a version requirement of `0.*`.

**Comment by KenPowers** [comment]
Decided not to deprecate the object. No real need to make that change since it's not hurting anybody. I guess next step would be to remove the peer dependency.

**Comment by w0rm** [comment]
Great, thank you! Regarding deprecation of configuration object, I'd like to have run function as the 1st parameter and options as the second optional one, I think it will be much cleaner than passing run function as an option.

**Comment by KenPowers** [comment]
We could support both.
